import { Suspense, lazy } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import HeaderSkeleton from "./components/Header/Skeleton";

const Header = lazy(() => import("./containers/Header/Header"));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
          <Suspense fallback={<HeaderSkeleton />}>
            <Header />
          </Suspense>
          <div className="flex flex-row items-start justify-center w-full overflow-y-auto">
            <div className="flex flex-start w-full">
              <aside className="bg-black flex w-1/5 min-h-screen"></aside>

              <main className="w-11/20">{children}</main>

              <aside className="bg-black flex w-1/4 min-h-screen"></aside>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
